modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
[[mods]]
modId="bricks"
version="${file.jarVersion}"
displayName="Bricks"
logoFile="bricks.png"
authors="Yggdraszil"
description='''
Decoration Blocks
'''

[[dependencies.bricks]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.bricks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"